ALTER TABLE WIRE
ADD CONSTRAINT FK_WIRE_FLOW_ID
FOREIGN KEY (FLOW_ID)
REFERENCES FLOW
ON DELETE CASCADE;

ALTER TABLE WIRE
ADD CONSTRAINT NO_EDGE_SELF_LOOP_ALLOWED
CHECK (SINK_NODE_ID <> SOURCE_NODE_ID);

ALTER TABLE WIRE
ADD CONSTRAINT DUPLICATE_EDGE_NOT_ALLOWED_IN_UNIDRECTED_GRAPH
CHECK (
    NOT EXISTS(
        SELECT *
        FROM WIRE w
        WHERE
          w.FLOW_ID = WIRE.FLOW_ID
          AND
          (w.SINK_NODE_ID = WIRE.SINK_NODE_ID AND w.SOURCE_NODE_ID = WIRE.SOURCE_NODE_ID)
          OR
          (w.SOURCE_NODE_ID = WIRE.SINK_NODE_ID AND w.SINK_NODE_ID = WIRE.SOURCE_NODE_ID)
    ));
